apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: avro-sub
  name: avro-sub-service-monitor
  namespace: lsnidero-test
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: /q/metrics
  selector:
    matchLabels:
      app: avro-sub
